[project]
name = "smflog"
version = "1.1.0"
authors = [
    {name = "StormWorld0", email = "StormWorld0@proton.me"}
]
description = "Fast logging library for Cloud Data Center (Microservices/Serverless)"
readme = "README.md"
requires-python = ">=3.9"
license = "GPL-2.0-only"
classifiers = [
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Natural Language :: Indonesian",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX",
    "Operating System :: POSIX :: BSD",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
keywords = [
    "python", "rust", "pyo3", "sqlite", "ffi",
    "developer-tools", "high-performance", "debugging", 
    "logger", "logging",
]

[project.urls]
homepage = "https://github.com/StormWorld0/smflog"
documentation = "https://github.com/StormWorld0/smflog/tree/main/README.md"
source = "https://github.com/StormWorld0/smflog"
issues = "https://github.com/StormWorld0/smflog/issues"
discussion = "https://github.com/orgs/StormWorld0/discussions"

[tool.maturin]
module-name = "smf"

[build-system]
requires = ["maturin>=1.14.1,<2"]
build-backend = "maturin"
